CREATE TABLE `CAM_AUTHORIZATION_INFO`  (
  `ID_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REGISTERED_CLIENT_ID_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRINCIPAL_NAME_` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `AUTHORIZATION_GRANT_TYPE_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ATTRIBUTES_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `STATE_` int CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `AUTHORIZATION_CODE_VALUE_` text NULL,
  `AUTHORIZATION_CODE_ISSUED_AT_` timestamp(0) NULL DEFAULT NULL,
  `AUTHORIZATION_CODE_EXPIRES_AT_` timestamp(0) NULL DEFAULT NULL,
  `AUTHORIZATION_CODE_METADATA_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `ACCESS_TOKEN_VALUE_` text NULL,
  `ACCESS_TOKEN_ISSUED_AT_` timestamp(0) NULL DEFAULT NULL,
  `ACCESS_TOKEN_EXPIRES_AT_` timestamp(0) NULL DEFAULT NULL,
  `ACCESS_TOKEN_METADATA_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `ACCESS_TOKEN_TYPE_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `ACCESS_TOKEN_SCOPES_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `OIDC_ID_TOKEN_VALUE_` text NULL,
  `OIDC_ID_TOKEN_ISSUED_AT_` timestamp(0) NULL DEFAULT NULL,
  `OIDC_ID_TOKEN_EXPIRES_AT_` timestamp(0) NULL DEFAULT NULL,
  `OIDC_ID_TOKEN_METADATA_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `REFRESH_TOKEN_VALUE_` text NULL,
  `REFRESH_TOKEN_ISSUED_AT_` timestamp(0) NULL DEFAULT NULL,
  `REFRESH_TOKEN_EXPIRES_AT_` timestamp(0) NULL DEFAULT NULL,
  `REFRESH_TOKEN_METADATA_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  PRIMARY KEY (`ID_`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;


CREATE TABLE `CAM_AUTHORIZATION_CONSENT`  (
  `REGISTERED_CLIENT_ID_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRINCIPAL_NAME_` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `AUTHORITIES_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`REGISTERED_CLIENT_ID_`, `PRINCIPAL_NAME_`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;



CREATE TABLE `CAM_REGISTERED_CLIENT`  (
  `ID_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CLIENT_ID_` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CLIENT_ID_ISSUED_AT_` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `CLIENT_SECRET_` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `CLIENT_SECRET_EXPIRES_AT_` timestamp(0) NULL DEFAULT NULL,
  `CLIENT_NAME_` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CLIENT_AUTHENTICATION_METHODS_` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `AUTHORIZATION_GRANT_TYPES_` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `REDIRECT_URIS_` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `SCOPES_` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CLIENT_SETTINGS_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TOKEN_SETTINGS_` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`ID_`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;